baseURL = "https://ai.corret.xyz/"
title = "AI弗一观"
theme = "hugo-liftoff"
enableRobotsTXT = true
enableEmoji = false
defaultContentLanguage = "zh-cn"

[pagination]
  pagerSize = 6

[params]
  description = "AI测评  AI资讯，人工智能"
  tagline = "AI弗一观 — 测评与资讯"
  copyrightOwner = "AI弗一观"
  copyrightSuffix = "All rights reserved."
  showFullContent = false
  mainSections = ["news", "test"]
  readingTimePerPage = 100

[params.footer]
  address = ""

[menus]
  [[menus.main]]
    name = "主页"
    pageRef = "/"
    weight = 5
  [[menus.main]]
    name = "AI资讯"
    pageRef = "/news"
    weight = 10
  [[menus.main]]
    name = "AI测评"
    pageRef = "/test"
    weight = 15

[markup]
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 3
    ordered = false
  [markup.highlight]
    style = "github-dark"
    noClasses = true
    lineNos = false
    codeFences = true
    tabWidth = 2
  [markup.goldmark.renderer]
    unsafe = true
    autoHeadingID = true
